### ISSUE TITLE
Can't start "Messkampagne" due to missing adapter type detection

### ISSUE THREAD

**Issue by drahnr** [flathub/de.breitbandmessung.Breitbandmessung#1]
![image](https://user-images.githubusercontent.com/667047/236833880-14b10ea7-0394-4031-9868-9f7e6eb6bd68.png)

**Comment by drahnr** [comment]
```
[2:0508/151616.297987:INFO:CONSOLE(2)] "%o: data.interfaces: [object Object] 2023-05-08T13:16:16.297Z", source: file:///app/extra/opt/Breitbandmessung/resources/app.asar/build/static/js/main.5e96aa81.chunk.js (2)
```

is an ever repeating error message.

The ethernet device name is `enp52s0f3u1u1`

**Comment by crepererum** [comment]
So this is either an upstream bug (in which case we won't patch it) or a problem related to the flatpak sandboxing.

@drahnr could you please test the build in #2 as described [here](https://github.com/flathub/de.breitbandmessung.Breitbandmessung/pull/2#issuecomment-1545787902)?

**Comment by drahnr** [comment]
Unfortunately no change.

**Comment by crepererum** [comment]
Then it's likely an upstream bug in which case you may contact the publisher. Note however that they don't endorse the flatpak handling, so they may refuse to help you because you haven't produces the issue on one of their officially supported systems.

I won't patch their code downstream since this is a license minefield and also makes the measurement produced by the flatpaked version questionable (at least it may support that argument). And if nobody believes that the flaktpaked version produces valid results, then this flatpak project here is kinda pointless (because there are better speed measurement tools for Linux out there).

**Comment by Ablu** [comment]
By debugging the app I figured that it wants to run `netstat -46 -rn | grep UG`. I know little about flatpak packaging, but I just hacked it by installing a `netstat` file into the image that does:
```
flatpak-spawn --host netstat "$@"
```
That fixes the "Messkampange".

Now of course that side-steps the permissions. The proper fix would be to include a netstat binary into the image (and ensure that it has the necessary access). Anyone a good idea how to do that? Will one have to build netstat from code?

**Comment by crepererum** [comment]
I think you would have to build `netstat` (it's part of [`net-tools`](https://net-tools.sourceforge.io/)). For that, we would need the following 3 parts:

Add `net-tools` to the sources here:

https://github.com/flathub/de.breitbandmessung.Breitbandmessung/blob/644b82d9d56556b8b5cfed6c3ece8976add536d2/de.breitbandmessung.Breitbandmessung.yml#L50

Build `netstat` and copy it over to the target folder here:

https://github.com/flathub/de.breitbandmessung.Breitbandmessung/blob/644b82d9d56556b8b5cfed6c3ece8976add536d2/de.breitbandmessung.Breitbandmessung.yml#L18

I think you should have a compiler available within the build sandbox (due to the SDK).

Adjust our license information because we now include GPL code:

https://github.com/flathub/de.breitbandmessung.Breitbandmessung/blob/644b82d9d56556b8b5cfed6c3ece8976add536d2/de.breitbandmessung.Breitbandmessung.metainfo.xml#L10

I think it should be possible to add two licenses here, following:

- https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license
- https://spdx.github.io/spdx-spec/v3.0/annexes/SPDX-license-expressions/

So this should be:

```xml
 <project_license>LicenseRef-proprietary=https://breitbandmessung.de/nutzungsbedingungen AND GPL-2.0-only</project_license> 
```

**Comment by Ablu** [comment]
> I think you would have to build netstat (it's part of [net-tools](https://net-tools.sourceforge.io/)).

Agreed! I might find some spare cycles on the weekend... But I am not making promises! So if anyone else wants to give it a try: go ahead! :P.

**Comment by Ablu** [comment]
Can someone else test https://github.com/flathub/de.breitbandmessung.Breitbandmessung/pull/9 to verify that it works on their end?

**Comment by Ablu** [comment]
Any chance to get a release that includes the fix for this on flathub.org? :innocent: 
I know that grabbing a build from the PR is easy, but I just had a friend also running into this problem.

Would be awesome if it would just work out of the box without having to manually build a version with the fix!

**Comment by crepererum** [comment]
The flathub build bot processed that `main` commit and should have uploaded the artifacts. Note that if you installed a PR build, you have to uninstall it to get back to the main branch.

**Comment by Ablu** [comment]
Ah. I somehow expected some version bump in the metadata would be require. But indeed. Reinstalling it properly on this machine fixed it at least. Maybe I also had it manually installed on the other machine...

Sorry for the noise!

Thanks again!
